--
-- PostgreSQL database dump
--

\restrict BQa2EpmOPyBJk8gcWDTpH6vHRkNrxfxifmeyfGEEZNKF0l7JqwXJeQBIz88JP3X

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

-- Started on 2026-04-23 09:46:55

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16432)
-- Name: ciudadanos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ciudadanos (
    id integer NOT NULL,
    numero_documento character varying(20) NOT NULL,
    nombres character varying(80) NOT NULL,
    apellidos character varying(80) NOT NULL,
    fecha_nacimiento date NOT NULL,
    vereda_barrio character varying(80) NOT NULL,
    telefono character varying(20),
    correo character varying(100),
    id_mesa integer,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ciudadanos OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16431)
-- Name: ciudadanos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ciudadanos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciudadanos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16400)
-- Name: ciudades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ciudades (
    id integer NOT NULL,
    nombre character varying(80) NOT NULL,
    departamento character varying(60) DEFAULT 'Boyacá'::character varying,
    codigo_dane character varying(10)
);


ALTER TABLE public.ciudades OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16399)
-- Name: ciudades_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ciudades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciudades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16446)
-- Name: documentos_expedidos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documentos_expedidos (
    id integer NOT NULL,
    id_ciudadano integer NOT NULL,
    tipo_documento character varying(50) NOT NULL,
    numero_serie character varying(30) NOT NULL,
    fecha_expedicion date NOT NULL,
    fecha_vencimiento date,
    observaciones character varying(300),
    imagen_documento character varying(500),
    estado character varying(20) DEFAULT 'vigente'::character varying
);


ALTER TABLE public.documentos_expedidos OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16445)
-- Name: documentos_expedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.documentos_expedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_expedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16420)
-- Name: mesas_votacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mesas_votacion (
    id integer NOT NULL,
    id_zona integer NOT NULL,
    numero_mesa integer NOT NULL,
    capacidad integer DEFAULT 200
);


ALTER TABLE public.mesas_votacion OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16419)
-- Name: mesas_votacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mesas_votacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mesas_votacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16460)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    documento character varying(20) NOT NULL,
    "contraseña" character varying(255) NOT NULL,
    tipo_usuario character varying(20) NOT NULL,
    estado character varying(20) DEFAULT 'activo'::character varying,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso timestamp without time zone
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16459)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16409)
-- Name: zonas_votacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.zonas_votacion (
    id integer NOT NULL,
    id_ciudad integer NOT NULL,
    nombre_zona character varying(80) NOT NULL,
    puesto_votacion character varying(120) NOT NULL,
    direccion character varying(150) NOT NULL
);


ALTER TABLE public.zonas_votacion OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16408)
-- Name: zonas_votacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.zonas_votacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.zonas_votacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3380 (class 0 OID 16432)
-- Dependencies: 221
-- Data for Name: ciudadanos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ciudadanos (id, numero_documento, nombres, apellidos, fecha_nacimiento, vereda_barrio, telefono, correo, id_mesa, fecha_registro) FROM stdin;
1	1052345678	Carlos Ernesto	Pedraza Rondón	1985-03-12	Centro	3101234567	\N	1	2026-04-14 07:16:20.853333
2	1052345679	María del Carmen	Suárez Cely	1992-07-24	Heroica	3117654321	\N	2	2026-04-14 07:16:20.853333
3	1052345680	Jorge Hernando	Báez Morales	1978-11-05	San Martín	3124567890	\N	4	2026-04-14 07:16:20.853333
4	1052345681	Luz Amparo	Chaparro Torres	2001-01-30	El Pino	3135678901	\N	6	2026-04-14 07:16:20.853333
5	1052345682	Pedro Antonio	Fonseca Nieto	1969-09-18	Belén	\N	\N	\N	2026-04-14 07:16:20.853333
6	1053584317	marly	barrera	2026-04-08	chameza alto	3125084171	marly@gmail.com	5	2026-04-22 10:39:57.692746
\.


--
-- TOC entry 3374 (class 0 OID 16400)
-- Dependencies: 215
-- Data for Name: ciudades; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ciudades (id, nombre, departamento, codigo_dane) FROM stdin;
1	Nobsa	Boyacá	15491
2	Sogamoso	Boyacá	15762
3	Duitama	Boyacá	15244
4	Bogotá D.C	Cundinamarca	09063
\.


--
-- TOC entry 3382 (class 0 OID 16446)
-- Dependencies: 223
-- Data for Name: documentos_expedidos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.documentos_expedidos (id, id_ciudadano, tipo_documento, numero_serie, fecha_expedicion, fecha_vencimiento, observaciones, imagen_documento, estado) FROM stdin;
1	1	Cédula de Ciudadanía	CC-2015-00123	2015-06-10	\N	\N	\N	vigente
3	3	Cédula de Ciudadanía	CC-2010-00789	2010-03-15	\N	\N	\N	vigente
5	5	Cédula de Ciudadanía	CC-2005-01345	2005-11-30	\N	\N	\N	vigente
2	2	Cedula de Ciudadania	CC-2018-00456	2018-09-22	2026-04-22		\N	vigente
4	4	Tarjeta de Identidad	TI-2016-01012	2016-08-01	2026-08-01	\N	\N	reemplazado
8	4	Tarjeta de Identidad	TI-2007-00456	2026-04-21	2026-05-02		doc_4_1776776270947_f95de0.jpg	reemplazado
9	4	Cedula de Ciudadania	TI-2007-00000	2026-04-22	2026-04-30	ppppp	doc_4_1776872502088_931a4d.jpg	reemplazado
\.


--
-- TOC entry 3378 (class 0 OID 16420)
-- Dependencies: 219
-- Data for Name: mesas_votacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mesas_votacion (id, id_zona, numero_mesa, capacidad) FROM stdin;
1	1	1	200
2	1	2	200
3	1	3	180
4	2	1	150
5	2	2	150
6	3	1	200
7	3	2	200
8	3	3	200
\.


--
-- TOC entry 3384 (class 0 OID 16460)
-- Dependencies: 225
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, username, documento, "contraseña", tipo_usuario, estado, fecha_registro, ultimo_acceso) FROM stdin;
2	maria.votante	1052345679	votante123	VOTANTE	activo	2026-04-15 14:09:36.576667	2026-04-21 08:05:44.191243
1	carlos.admin	1052345678	admin123	ADMIN	activo	2026-04-15 14:09:36.576667	2026-04-22 10:38:08.104095
3	jorge.votante	1052345680	jorge123	VOTANTE	inactivo	2026-04-15 14:09:36.576667	\N
4	luz.votante	1052345681	luz123	VOTANTE	activo	2026-04-15 14:09:36.576667	2026-04-22 10:43:05.255767
\.


--
-- TOC entry 3376 (class 0 OID 16409)
-- Dependencies: 217
-- Data for Name: zonas_votacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.zonas_votacion (id, id_ciudad, nombre_zona, puesto_votacion, direccion) FROM stdin;
1	1	Zona Centro	Institución Educativa Nobsa	Calle 5 # 4-32, Centro
2	1	Zona Heroica	Escuela Rural La Heroica	Vereda La Heroica s/n
3	1	Zona Norte	Colegio Técnico Industrial de Nobsa	Carrera 3 # 8-15, Norte
\.


--
-- TOC entry 3390 (class 0 OID 0)
-- Dependencies: 220
-- Name: ciudadanos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ciudadanos_id_seq', 6, true);


--
-- TOC entry 3391 (class 0 OID 0)
-- Dependencies: 214
-- Name: ciudades_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ciudades_id_seq', 4, true);


--
-- TOC entry 3392 (class 0 OID 0)
-- Dependencies: 222
-- Name: documentos_expedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documentos_expedidos_id_seq', 9, true);


--
-- TOC entry 3393 (class 0 OID 0)
-- Dependencies: 218
-- Name: mesas_votacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mesas_votacion_id_seq', 8, true);


--
-- TOC entry 3394 (class 0 OID 0)
-- Dependencies: 224
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 4, true);


--
-- TOC entry 3395 (class 0 OID 0)
-- Dependencies: 216
-- Name: zonas_votacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.zonas_votacion_id_seq', 3, true);


--
-- TOC entry 3213 (class 2606 OID 16439)
-- Name: ciudadanos ciudadanos_numero_documento_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudadanos
    ADD CONSTRAINT ciudadanos_numero_documento_key UNIQUE (numero_documento);


--
-- TOC entry 3215 (class 2606 OID 16437)
-- Name: ciudadanos ciudadanos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudadanos
    ADD CONSTRAINT ciudadanos_pkey PRIMARY KEY (id);


--
-- TOC entry 3205 (class 2606 OID 16407)
-- Name: ciudades ciudades_codigo_dane_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudades
    ADD CONSTRAINT ciudades_codigo_dane_key UNIQUE (codigo_dane);


--
-- TOC entry 3207 (class 2606 OID 16405)
-- Name: ciudades ciudades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudades
    ADD CONSTRAINT ciudades_pkey PRIMARY KEY (id);


--
-- TOC entry 3217 (class 2606 OID 16453)
-- Name: documentos_expedidos documentos_expedidos_numero_serie_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos_expedidos
    ADD CONSTRAINT documentos_expedidos_numero_serie_key UNIQUE (numero_serie);


--
-- TOC entry 3219 (class 2606 OID 16451)
-- Name: documentos_expedidos documentos_expedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos_expedidos
    ADD CONSTRAINT documentos_expedidos_pkey PRIMARY KEY (id);


--
-- TOC entry 3211 (class 2606 OID 16425)
-- Name: mesas_votacion mesas_votacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mesas_votacion
    ADD CONSTRAINT mesas_votacion_pkey PRIMARY KEY (id);


--
-- TOC entry 3221 (class 2606 OID 16470)
-- Name: usuarios usuarios_documento_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_documento_key UNIQUE (documento);


--
-- TOC entry 3223 (class 2606 OID 16466)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 3225 (class 2606 OID 16468)
-- Name: usuarios usuarios_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_username_key UNIQUE (username);


--
-- TOC entry 3209 (class 2606 OID 16413)
-- Name: zonas_votacion zonas_votacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas_votacion
    ADD CONSTRAINT zonas_votacion_pkey PRIMARY KEY (id);


--
-- TOC entry 3228 (class 2606 OID 16440)
-- Name: ciudadanos ciudadanos_id_mesa_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudadanos
    ADD CONSTRAINT ciudadanos_id_mesa_fkey FOREIGN KEY (id_mesa) REFERENCES public.mesas_votacion(id);


--
-- TOC entry 3229 (class 2606 OID 16454)
-- Name: documentos_expedidos documentos_expedidos_id_ciudadano_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos_expedidos
    ADD CONSTRAINT documentos_expedidos_id_ciudadano_fkey FOREIGN KEY (id_ciudadano) REFERENCES public.ciudadanos(id);


--
-- TOC entry 3227 (class 2606 OID 16426)
-- Name: mesas_votacion mesas_votacion_id_zona_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mesas_votacion
    ADD CONSTRAINT mesas_votacion_id_zona_fkey FOREIGN KEY (id_zona) REFERENCES public.zonas_votacion(id);


--
-- TOC entry 3230 (class 2606 OID 16471)
-- Name: usuarios usuarios_documento_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_documento_fkey FOREIGN KEY (documento) REFERENCES public.ciudadanos(numero_documento);


--
-- TOC entry 3226 (class 2606 OID 16414)
-- Name: zonas_votacion zonas_votacion_id_ciudad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.zonas_votacion
    ADD CONSTRAINT zonas_votacion_id_ciudad_fkey FOREIGN KEY (id_ciudad) REFERENCES public.ciudades(id);


-- Completed on 2026-04-23 09:46:56

--
-- PostgreSQL database dump complete
--

\unrestrict BQa2EpmOPyBJk8gcWDTpH6vHRkNrxfxifmeyfGEEZNKF0l7JqwXJeQBIz88JP3X

